version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.1.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: restaurant
    ports:
      - "5432:5432"

  discovery-service:
    build: ./discovery-service
    ports:
      - "8761:8761"

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery-service

  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"
    depends_on:
      - discovery-service

  order-service:
    build: ./order-service
    ports:
      - "8082:8082"
    depends_on:
      - discovery-service
      - kafka

  notification-service:
    build: ./notification-service
    ports:
      - "8083:8083"
    depends_on:
      - discovery-service
      - kafka

  menu-service:
    build: ./menu-service
    ports:
      - "8084:8084"
    depends_on:
      - discovery-service
      - kafka
      - postgres
