spring:
    application:
        name: order-service
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            group-id: order-service
            auto-offset-reset: earliest
server:
    port: 8082

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/